# Generated by Django 4.1.7 on 2023-03-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_acessorio_cor_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
    ]
